PassTrackingSystem/Controllers/SinglePassController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PassTrackingSystem.Extensions;
using PassTrackingSystem.Models;
using PassTrackingSystem.Models.Repositoryes;
using PassTrackingSystem.Models.SeparatorOnThePage;
using PassTrackingSystem.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PassTrackingSystem.Controllers
{
    [Authorize]
    public class SinglePassController : Controller
    {
        private readonly IGenericRepository<SinglePass> passRepository;
        private readonly IGenericRepository<StationFacility> stationFacilitysRepository;
        private readonly IGenericRepository<Employee> employeeRepository;
        private readonly UserManager<AppUser> userManager;
        public SinglePassController(IGenericRepository<SinglePass> passRepository,
            IGenericRepository<StationFacility> stationFacilitysRepository,
            IGenericRepository<Employee> employeeRepository, UserManager<AppUser> userManager)
        {
            this.employeeRepository = employeeRepository;
            this.stationFacilitysRepository = stationFacilitysRepository;
            this.passRepository = passRepository;
            this.userManager = userManager;
        }

        public async Task<IActionResult> SinglePassProcessing(int id, int visitorId)
        {
            SinglePass singlePass;
            if (id != 0)
            {
                singlePass = await passRepository.GetAll()
                    .Where(v => v.Id == id)
                    .Include(v => v.StationFacilities)
                    .Include(v => v.SinglePassIssued)
                    .ThenInclude(v => v.Department)
                    .FirstAsync();
            }
            else
            {
                if (visitorId != 0)
                {
                    singlePass = new SinglePass();
                    singlePass.SinglePassIssued= await GetRequestUserAsync();
                    singlePass.ValidWith = DateTime.Now;
                    singlePass.ValitUntil = DateTime.Now;
                    singlePass.VisitorId = visitorId;
                }
                else return new BadRequestResult();

            }
            return View(new SinglePassVM
            {
                ProcessingSinglePass = singlePass,
                ShowAdvancedFeatures = HttpContext.User.IsInRole("Administrator") || HttpContext.User.IsInRole("Moderator")
            });
        }
        [HttpPost, Authorize(Roles = "Moderator, Administrator")]
        public async Task<RedirectToActionResult> SinglePassProcessing(SinglePass ProcessingSinglePass,
            List<int> facilitiesId)
        {
            await passRepository.Update(ProcessingSinglePass);
            passRepository.GetAll().Include(v => v.StationFacilities).
                Where(v => v.Id == ProcessingSinglePass.Id)
                .First();

            ProcessingSinglePass.StationFacilities =
                await Task.Run(() => facilitiesId.Select(id => stationFacilitysRepository.GetAll()
               .Include(v => v.SinglePasses)
              .Where(v => v.Id == id).First()).ToList());
            ProcessingSinglePass.SinglePassIssued = await GetRequestUserAsync();
            await passRepository.Update(ProcessingSinglePass);
            int id = ProcessingSinglePass.Id;
            return RedirectToAction("SinglePassProcessing", new { id = id });
        }

        public async Task<IActionResult> ShowAll(int? visitorId, CommonListQuery options = null)
        {
            var query = visitorId == null ? passRepository.GetAll() : passRepository.GetAll()
                .Where(v => v.VisitorId == visitorId);
            if (options.SearchСolumn == nameof(ShootingPermission.StationFacilities))
            {
                query = query.Where(t => t.StationFacilities.Any(f => f.Value.Contains(options.SearchValue)));
                options.SearchСolumn = "";
            }
            var passes = Task.Run(() => new PagesDividedList<SinglePass>(query
                  .Include(v => v.StationFacilities)
                  .Include(v => v.SinglePassIssued)
                  .ThenInclude(v => v.Department)
                     .SearchByMember(options.SearchСolumn, options.SearchValue)
                        .OrderByMember("Id", true), options.CurrentPage, options.PageSize));
            if (visitorId != 0)
            {
                ViewBag.CurrentPage = "all-SinglePass";
            }
            var singlePasses = await passes;
            return View(new SinglePassVM { SinglePasses = await passes, PurposeVisitorId = visitorId,
                ShowAdvancedFeatures = HttpContext.User.IsInRole("Administrator") || HttpContext.User.IsInRole("Moderator")
            });
        }

        public async Task<IActionResult> GetAllowedList(int processingPass)
        {
            var pass = await passRepository.GetAll()
                .Where(v => v.Id == processingPass)
                .Include(v => v.StationFacilities).FirstOrDefaultAsync();
            if (pass == null)
            {
                pass = new SinglePass();
                pass.StationFacilities = new List<StationFacility>();

            }
            var allPass = await stationFacilitysRepository.GetAll().ToListAsync();
            var accessPairs = allPass.Select(s => new
            {
                Facility = s,
                Allow = pass.StationFacilities
                .Where(v => v.Id == s.Id)
                .Any()
            })
                .ToDictionary(v => v.Facility, i => i.Allow);
            return View(accessPairs);
        }

        public async Task<IActionResult> Document(int passId, bool itsForDocument=true)
        {
            if (passId != 0)
            {
                var pass = await passRepository.GetAll()
                    .Where(p => p.Id == passId)
                    .Include(p => p.Visitor).ThenInclude(v => v.Document).ThenInclude(d => d.DocumentType)
                    .Include(p => p.Visitor).ThenInclude(v => v.Document).ThenInclude(d => d.IssuingAuthority)
                    .Include(p => p.StationFacilities)
                    .FirstAsync();

                var documentVM = new CommonInformationVM
                {
                    Document = pass.Visitor.Document,
                    Id = pass.Id,
                    Name = pass.Visitor.Name,
                    LastName = pass.Visitor.LastName,
                    Patronymic = pass.Visitor.LastName,
                    PassType = "Разовый пропуск",
                    ValidWith = pass.ValidWith.ToString("dd:mm  yyyy-hh-mm"),
                    ValitUntil = pass.ValitUntil.ToString("dd:mm  yyyy-hh-mm"),
                    PlaceOfWork = pass.Visitor.PlaceOfWork,
                    Position = pass.Visitor.Position,
                    PurposeOfIssuance = pass.PurposeOfIssuance,
                    StationFacilities = pass.StationFacilities.Select(f => f.Value).ToList()
                };
                if (itsForDocument)
                {
                    return View("Document", documentVM);
                }
                if (!itsForDocument)
                {
                    return View("CommonPassInfo", documentVM);
                }

            }
            return BadRequest();
        }

        [HttpPost, Authorize(Roles = "Moderator, Administrator")]
        public async Task<IActionResult> Delete(int id)
        {
            if (id != 0)
            {
                await passRepository.Delete(id);
            }
            return new OkResult();
        }

        public IActionResult BadRedirectRequest() => BadRequest();

        private async Task<Employee> GetRequestUserAsync()
        {
            var user = await userManager.GetUserAsync(HttpContext.User);
            return await employeeRepository.Get(user.EmployeeId);
        }
    }
}

PassTrackingSystem/Views/SinglePass/GetAllowedList.cshtml
@{
    Layout = "";
}
@model Dictionary<StationFacility, bool>
<div class="accordion accordion-flush pt-4" id="accordionFlushExample">
    <div class="accordion-item">
        <h2 class="accordion-header border-2" id="flush-headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                Обьекты для посещения
            </button>
        </h2>
        <div id="flush-collapseOne" class="accordion-collapse collapse show" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body" style="background-color: rgb(250, 250, 250);">
                @foreach (var item in Model)
                {
                    <span style="white-space: nowrap;" class="m-3">
                        <input class="form-check-input" type="checkbox" value="@item.Key.Id" id="flexCheckChecked"
                               @if (item.Value) { <text> checked</text>} name="facilitiesId">
                        <label class="form-check-label" for="flexCheckChecked">
                            @item.Key.Value
                        </label>
                    </span>
                }
            </div>
        </div>
    </div>
</div>

PassTrackingSystem/Views/SinglePass/ShowAll.cshtml
@model SinglePassVM

@{
    ViewData["Title"] = "Home Page";
}

<div class="col-12">
    <form asp-action="@nameof(PassTrackingSystem.Controllers.SinglePassController.ShowAll)"
          asp-controller="@nameof(PassTrackingSystem.Controllers.SinglePassController).Replace("Controller", "")"
          id="info-option-group" method="get">
        @await Html.PartialAsync("UpperOptionMenu", @Model)
        <input type="hidden" value="@Model.PurposeVisitorId" name="visitorId" />
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col" class="th-sm">id</th>
                    <th scope="col">Действует с</th>
                    <th scope="col">Действует по</th>
                    <th scope="col">Цель выдачи</th>
                    <th scope="col">Места для посещения</th>
                    <th scope="col">Лицо выдавшее пропуск</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var singlePass in Model.SinglePasses.Items)
                {
                    <tr>
                        <td>@singlePass.Id</td>
                        <td>@singlePass.ValidWith.ToShortDateString()</td>
                        <td>@singlePass.ValitUntil.ToShortDateString()</td>
                        <td>@singlePass.PurposeOfIssuance</td>
                        <td>
                            @foreach (var item in singlePass.StationFacilities)
                            {
                                <text>@item.Value<br></text>
                            }
                        </td>
                        <td>@singlePass.SinglePassIssued.LastName @singlePass.SinglePassIssued.Name @singlePass.SinglePassIssued.Patronymic</td>
                        <td>
                            <a asp-action="@nameof(PassTrackingSystem.Controllers.SinglePassController.SinglePassProcessing)"
                               asp-controller="@nameof(PassTrackingSystem.Controllers.SinglePassController).Replace("Controller", "")"
                               asp-route-id="@singlePass.Id"
                               class="btn btn-outline-dark">Подробнее</a>
                        </td>
                        @if (Model.ShowAdvancedFeatures)
                        {
                            <td>
                                <button class="btn btn-outline-danger delete" del-id="@singlePass.Id">
                                    Удалить
                                </button>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
        @await Html.PartialAsync("Pages", @Model.SinglePasses.PageDividorInfo)
    </form>
    <script>
        $('.delete').click(function (e) {
            $.post('@Url.RouteUrl(new { controller = nameof(SinglePassController).Replace("Controller", ""),
              action = nameof(SinglePassController.Delete)})', { id: $(this).attr('del-id') }, function () { location.reload()})
              e.preventDefault()
        })
    </script>
</div>

PassTrackingSystem/Views/SinglePass/SinglePassProcessing.cshtml
@model SinglePassVM
<form method="post" asp-controller="SinglePass" , asp-action="SinglePassProcessing">
    <div class="container-fluid set-min-width">
        <input type="hidden" asp-for="ProcessingSinglePass.Id" id="pass-id" />
        <input type="hidden" asp-for="ProcessingSinglePass.VisitorId" />
        <div class="row">
            <div class="col-md-6">
                <label asp-for="ProcessingSinglePass.ValidWith" class="form-label">Действует с</label>
                <input asp-for="ProcessingSinglePass.ValidWith" class="form-control">
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label asp-for="ProcessingSinglePass.ValitUntil" class="form-label">Действует по</label>
                <input asp-for="ProcessingSinglePass.ValitUntil" class="form-control">
            </div>
        </div>
        <div class="row">
            <div class="col-md-7">
                <label asp-for="ProcessingSinglePass.PurposeOfIssuance" class="form-label">Цель выдачи</label>
                <textarea asp-for="ProcessingSinglePass.PurposeOfIssuance" class="form-control" rows="6"></textarea>
            </div>
        </div>
    </div>
    <div id="access-list">
    </div>
    <div class="pt-4 bd-example">
        <label>Сотрудник выдавший документ</label>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Имя</th>
                    <th scope="col">Фамилия</th>
                    <th scope="col">Отчество</th>
                    <th scope="col">Подразделение</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model?.ProcessingSinglePass?.SinglePassIssued?.LastName</td>
                    <td>@Model?.ProcessingSinglePass?.SinglePassIssued?.Name</td>
                    <td>@Model?.ProcessingSinglePass?.SinglePassIssued?.Position</td>
                    <td>@Model?.ProcessingSinglePass?.SinglePassIssued?.Department?.Value</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="py-5 ">
        <button type="submit" class="btn btn-success">Отправить</button>
        <button type="reset" class="btn btn-danger">Очистить</button>
        @if (Model.ProcessingSinglePass?.Id != 0)
        {
            <a class="btn btn-info"
               asp-controller=@nameof(SinglePassController).Replace("Controller", "")
               asp-action="@nameof(SinglePassController.Document)" asp-route-passId="@Model.ProcessingSinglePass.Id">Генерировать документ</a>
        }
    </div>

</form>
<script>
    $('document').ready(function (e) {
        $('#access-list').load('@Url.RouteUrl(new
{
    controller = nameof(SinglePassController).Replace("Controller", ""),
                       action = nameof(SinglePassController.GetAllowedList)
                   })', { processingPass: $('#pass-id').val() })
    })
</script>