PassTrackingSystem/Models/Document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PassTrackingSystem.Models
{
    public class Document
    {
        public int Id { get; set; }
        [Required]
        public string Series { get; set; }
        [Required]
        public string Number { get; set; }
        [Required, DataType(DataType.Date)]
        public DateTime DateOfIssue { get; set; }
        [Required]
        public int DocumentTypeId { get; set; }
        public  DocumentType DocumentType { get; set; }
        [Required]
        public int IssuingAuthorityId { get; set; }
        public IssuingAuthority IssuingAuthority { get; set; }
        public Visitor Visitor { get; set; }
        public int VisitorId { get; set; }
    }
}

PassTrackingSystem/Models/DocumentType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PassTrackingSystem.Models
{
    public class DocumentType : IOneValueCommon
    {
        public int Id { get; set; }
        [Required]
        public string Value { get; set; }
    }
}

PassTrackingSystem/Controllers/CommonPassInfoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PassTrackingSystem.Controllers
{
    public class CommonPassInfoController : Controller
    {
       public RedirectToActionResult CommonPassInfo(int searchId, int searchType)
        {
           if(searchId!=0)
            {
                switch (searchType)
                {
                    case 1:
                        return RedirectToAction(nameof(SinglePassController.Document), nameof(SinglePassController).Replace("Controller", ""), 
                            new {passId = searchId, itsForDocument= false });
                    case 2:
                        return RedirectToAction(nameof(TemporaryPassController.Document), nameof(TemporaryPassController).Replace("Controller", ""),
                             new { passId = searchId, itsForDocument = false });
                    case 3:
                        return RedirectToAction(nameof(CarPassController.Document), nameof(CarPassController).Replace("Controller", ""),
                             new { passId = searchId, itsForDocument = false });
                    case 4:
                        return RedirectToAction(nameof(ShootingPermissionController.Document), nameof(ShootingPermissionController).Replace("Controller", ""),
                             new { passId = searchId, itsForDocument = false });
                }
            }
            return RedirectToAction("error");
        } 

    }
}

PassTrackingSystem/Views/Shared/CommonPassInfo.cshtml
@model CommonInformationVM

<div style="max-width: 210mm; max-height: 297mm;">
    <div class="container-fluid">
        <h5 class="text-center">@Model.PassType &nbsp №@Model.Id</h5>
        <div class="row">          
                <div class="container-fluid">
                    <div class="col">
                        <div>Фамилия: @Model.LastName</div>
                    </div>
                    <div class="col my-1">
                        <div>Имя: @Model.Name</div>
                    </div>
                    <div class="col my-1">
                        <div>Отчество: @Model.Patronymic</div>
                    </div>
                    <div class="col my-1">
                        <div>Место работы: @Model.PlaceOfWork</div>
                    </div>
                    <div class="col my-1">
                        <div>Должность: @Model.Position</div>
                    </div>
                    <div class="col my-2">
                        <div>В случае отсутствия фотографии, временный пропуск  действителен только при наличии документа на  основании которого он выписан</div>
                    </div>
                </div>
        </div>
        <div class="row mt-3">
            <div class="col"> Пропуск выдан на основании: @Model.Document.DocumentType.Value</div>
        </div>
        <div class="row my-1">
            <div class="col-4"> Серия: @Model.Document.Series, Номер: @Model.Document.Number</div>
        </div>
        <div class="row my-1">
            <div class="col">Кем выдан: @Model.Document.IssuingAuthority.Value </div>
        </div>
        <div class="row my-1">
            <div class="col">Дата выдачи: @Model.Document.DateOfIssue.ToShortDateString() </div>
        </div>
        <div class="row mt-3">
            <div class="col">Пропуск действует с: @Model.ValidWith </div>
        </div>
        <div class="row my-1">
            <div class="col">Пропуск действует до: @Model.ValitUntil </div>
        </div>
        <div class="row mt-3">
            <div class="col">Цель выдачи: @Model.PurposeOfIssuance</div>
        </div>
        <div class="row mt-3">
            <div class="col">Дополнительная информация:  </div>
        </div>
        <div class="row my-1 fixed-bottom mt-3">
            <div class="col">Дата выдачи: 12.12.2020 </div>
        </div>
        @if (Model?.StationFacilities?.Count > 0)
        {
            <div class="row mt-3">
                <div class="col">
                    Обьекты для посещения: @foreach (var item in Model.StationFacilities)
                    {
                        @item <text>, </text>
                    }
                </div>
            </div>
        }

        @if (!string.IsNullOrEmpty(Model.CameraType))
        {
            <div class="row">
                <div class="col">
                    Модель камеры: @Model.CameraType
                </div>
            </div>
        }

        @if (Model.Car != null)
        {
            <div class="row">
                <div class="col">
                    Марка автомобиля: @Model.Car.CarBrand
                </div>
            </div>
            <div class="row">
                <div class="col">
                    Номерной знак: @Model.Car.CarLicensePlate
                </div>
            </div>
        }
    </div>
</div>

PassTrackingSystem/Views/Shared/Document.cshtml
@model CommonInformationVM
@{
    Layout = "";
}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>

<body style="max-width: 210mm; max-height: 297mm;">
    <div class="container-fluid">
        <h2 class="text-center">@Model.CompanyName</h2>
        <h5 class="text-center">@Model.PassType &nbsp №@Model.Id</h5>
        <div class="row pt-4">
            <div class="col-3">
                <div class="card" style="width: 12rem; height: 14rem;">
                    <div class="card-body"
                         style="position: absolute; top: 50%; left: 50%;  transform: translate(-50%, -50%);">
                        <h6>Фото</h6>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="container-fluid">
                    <div class="col">
                        <div>Фамилия: @Model.LastName</div>
                    </div>
                    <div class="col my-1">
                        <div>Имя: @Model.Name</div>
                    </div>
                    <div class="col my-1">
                        <div>Отчество: @Model.Patronymic</div>
                    </div>
                    <div class="col my-1">
                        <div>Место работы: @Model.PlaceOfWork</div>
                    </div>
                    <div class="col my-1">
                        <div>Должность: @Model.Position</div>
                    </div>
                    <div class="col my-2">
                        <div>В случае отсутствия фотографии, временный пропуск  действителен только при наличии документа на  основании которого он выписан</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col"> Пропуск выдан на основании: @Model.Document.DocumentType.Value</div>
        </div>
        <div class="row my-1">
            <div class="col-4"> Серия: @Model.Document.Series, Номер: @Model.Document.Number</div>
        </div>
        <div class="row my-1">
            <div class="col">Кем выдан: @Model.Document.IssuingAuthority.Value </div>
        </div>
        <div class="row my-1">
            <div class="col">Дата выдачи: @Model.Document.DateOfIssue.ToShortDateString() </div>
        </div>
        <div class="row mt-3">
            <div class="col">Пропуск действует с: @Model.ValidWith </div>
        </div>
        <div class="row my-1">
            <div class="col">Пропуск действует до: @Model.ValitUntil </div>
        </div>
        <div class="row mt-3">
            <div class="col">Цель выдачи: @Model.PurposeOfIssuance</div>
        </div>
        <div class="row mt-3">
            <div class="col">Дополнительная информация:  </div>
        </div>
        <div class="row my-1 fixed-bottom mt-3">
            <div class="col">Дата выдачи: 12.12.2020 </div>
        </div>
        @if (Model?.StationFacilities?.Count > 0)
        {
            <div class="row mt-3">
                <div class="col">
                    Обьекты для посещения: @foreach (var item in Model.StationFacilities)
                    {
                        @item <text>, </text>
                    }
                </div>
            </div>
        }

        @if (!string.IsNullOrEmpty(Model.CameraType))
        {
            <div class="row">
                <div class="col">
                    Модель камеры: @Model.CameraType
                </div>
            </div>
        }

        @if (Model.Car != null)
        {
            <div class="row">
                <div class="col">
                    Марка автомобиля: @Model.Car.CarBrand
                </div>
            </div>
            <div class="row">
                <div class="col">
                    Номерной знак: @Model.Car.CarLicensePlate
                </div>
            </div>
        }
    </div>
</body>
</html>

PassTrackingSystem/Views/Shared/Pages.cshtml
@model PassTrackingSystem.Models.SeparatorOnThePage.PageDividorInfo
<div class="container-fluid pading-left-z" id="PageGroup" style="padding-left: 0px;">
    <div class="container-fluid">
        <div class="row">
            <div class="col-5" style="padding-left: 0px;">
                <div class="input-group mb-3 " id="count-page-form">
                    <input type="text" name="CurrentPage" class="form-control " placeholder="№" min="1" max="@Model.TotalPages" value="@Model.CurrentPage" id="current-Page">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Перейти на страницу</button>
                </div>
            </div>
            <div class="col-5">
                <div class="input-group">
                    <select class="form-select" id="inputGroupSelect04" name="PageSize" aria-label="Example select with button addon" style="box-sizing:unset;">
                        @for (int i = 20; i < 200; i = i * 2)
                        {
                            if (i == Model.PageSize)
                            {
                                <option selected value="@i">@i</option>
                            }
                            else
                            {
                                <option value="@i">@i</option>
                            }
                        }
                    </select>
                    <button class="btn btn-outline-secondary" type="submit" id="change-quantity-elem">сменить кол-во элементов</button>
                </div>
            </div>
        </div>
    </div>

    @if (Model.TotalPages >= 4)
    {
        var changePageClass = "change-page-button";
        var CurrentPage = Model.CurrentPage;
        var CountSideButtom = 3;
        if (Model.HasPreviousPage)
        {
            var prevPage = Model.CurrentPage - 1;
            <button name="CurrentPage" class="btn btn-secondary" value="@prevPage">Пред</button>
        }
        var maxViewPage = 0;

        if (CurrentPage > CountSideButtom + 1)
        {
            <button name="CurrentPage" class="btn btn-secondary @changePageClass"
                    value="1">
                1
            </button>
            <span>....</span>
        }

        @for (int i = CurrentPage - CountSideButtom; i < CurrentPage; i++)
        {
            maxViewPage = i + 1;
            if (i > 0)
            {
                <button name="CurrentPage" class="btn btn-secondary @changePageClass"
                        value="@i">
                    @i
                </button>
            }
        }
        <button name="CurrentPage" class="btn btn-dark @changePageClass"
                value="@CurrentPage">
            @CurrentPage
        </button>

        @for (int i = CurrentPage + 1; i <= CurrentPage + CountSideButtom && i <= Model.TotalPages; i++)
        {
            maxViewPage = i;
            <button name="CurrentPage" class="btn btn-secondary @changePageClass"
                    value="@i">
                @i
            </button>
        }

        if (maxViewPage != Model.TotalPages)
        {
            <span>....</span>
            <button name="CurrentPage" class="btn btn-secondary @changePageClass"
                    value="@Model.TotalPages">
                @Model.TotalPages
            </button>
        }

        if (Model.HasNextPage)
        {
            var prevPage = Model.CurrentPage + 1;
            <button name="CurrentPage" class="btn btn-secondary @changePageClass" value="@prevPage">След</button>
        }

    }
    else
    {
        @if (Model.TotalPages>1)
        {
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                <button name="CurrentPage" class="btn btn-secondary change-page-button" value="@i">@i</button>
            }       
        
        }
    }
    <script>
        $('.change-page-button').click(function (e) {
            $('#current-Page')
                .attr('value', $(this)
                    .attr('value'));
            $('#button-addon2')
                .trigger('click');
            e.preventDefault()
        })
    </script>
</div>

PassTrackingSystem/Views/Shared/Styles.cshtml
<style class="anchorjs"></style>
<link href="/MaimL_files/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<link href="/MaimL_files/docs.css" rel="stylesheet">

PassTrackingSystem/Views/Shared/UpperOptionMenu.cshtml
@model ITableWithOptionsVM
<div class="container-fluid">
    <div class="row">
        <div class="col-9 mb-3" style="padding-left: 0px;">
            <div class="input-group">
                <button class="btn btn-outline-secondary" type="submit" id="search-pagedevidlist">Поиск</button>
                <select class="form-select" id="inputGroupSelect01" name="SearchСolumn">
                    @foreach (var item in Model.HeadNames)
                    {
                        if (item.Value == Model.Options?.SearchСolumn)
                        {
                            <option selected value="@item.Value">@item.Key</option>
                        }
                        else
                        {
                            <option value="@item.Value">@item.Key</option>
                        }
                    }
                </select>
                <input type="text" aria-label="Last name" class="form-control" name="SearchValue" value="@Model.Options?.SearchValue">
            </div>
        </div>
    </div>
    <script>
        $('#search-pagedevidlist').click(function (e) {
            $('#current-Page')
                .attr('value', '1');
        })       
    </script>
</div>

PassTrackingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Station passes</title>
    <meta http-equiv="Cache-Control" content="private">
    @await Html.PartialAsync("Styles")
    @await Html.PartialAsync("_ValidationScriptsPartial")

</head>
<body>
    <input type="hidden" value="@ViewBag.CurrentPage" id="currentPage"/>
    <header class="navbar navbar-expand-md navbar-dark bd-navbar">
        <nav class="container-xxl flex-wrap flex-md-nowrap" aria-label="Main navigation">
            <img src="/Logo-ru-ng.png" alt="альтернативный текст" style="width:25%; height:25%;">
        </nav>
    </header>
    <nav class="bd-subnavbar py-2" aria-label="Secondary navigation">
        <form class="container-xxl d-flex align-items-md-center" asp-controller="CommonPassInfo", asp-action="CommonPassInfo">
                <div class="input-group ms-3" style="max-width :20%">
                    <button class="btn btn-outline-secondary" type="submit" id="button-pass-search">Поиск</button>
                    <input type="text" class="form-control" placeholder="" data-val="true" data-val-required="error" name="searchId" aria-label="Example text with button addon" aria-describedby="button-addon1">
                </div>
                <div class="dropdown ms-3 flex-grow-1">
                    <select class="form-select align" name="searchType" aria-label="Default select example" style="max-width:40%">
                        <option value="1">Разовый пропуск</option>
                        <option value="2">Временный пропуск</option>
                        <option value="3">Транспортный пропуск</option>
                        <option value="4">Разрешение на съемку</option>
                    </select>
                </div>
                @await Component.InvokeAsync("UpperUserComponent")
        </form>
    </nav>

    <div class="container-xxl my-md-4 bd-layout">
        <aside class="bd-sidebar">
            <nav class="collapse bd-links" id="bd-docs-nav" aria-label="Docs navigation">
                <ul class="list-unstyled mb-0 py-3 pt-md-1">
                    <li class="mb-1">
                        <button class="btn d-inline-flex align-items-center rounded" data-bs-toggle="collapse" data-bs-target="#getting-started-collapse" aria-expanded="true" aria-current="true">
                            Посетитель
                        </button>
                        <div class="collapse show" id="getting-started-collapse">
                            <ul class="list-unstyled fw-normal pb-1 small">
                                <li>
                                    <a asp-action="@nameof(PassTrackingSystem.Controllers.VisitorFormController.VisitorProcessing)"
                                       asp-controller="@nameof(PassTrackingSystem.Controllers.VisitorFormController).Replace("Controller", "")"
                                       asp-route-id="0" class="d-inline-flex align-items-center rounded"
                                       id="add-VisitorForm">Добавить новый</a>
                                </li>
                                <li>
                                    <a asp-action="@nameof(PassTrackingSystem.Controllers.HomeController.Index)"
                                       asp-controller="@nameof(PassTrackingSystem.Controllers.HomeController).Replace("Controller", "")"
                                       class="d-inline-flex align-items-center rounded" aria-current="page"
                                       id="all-HomeController">Просмотреть всех</a>
                                </li>
                            </ul>
                        </div>
                    <li class="mb-1">
                        <button class="btn d-inline-flex align-items-center rounded" data-bs-toggle="collapse" data-bs-target="#getting-started-collapse" aria-expanded="true" aria-current="true">
                            Пропуска
                        </button>
                        <div class="collapse show" id="getting-started-collapse">
                            <ul class="list-unstyled fw-normal pb-1 small">
                                <li class="d-inline-flex align-items-center rounded " aria-current="page">
                                    <a asp-action="@nameof(PassTrackingSystem.Controllers.TemporaryPassController.ShowAll)"
                                       asp-controller="@nameof(PassTrackingSystem.Controllers.TemporaryPassController).Replace("Controller", "")"
                                       id="all-TemporaryPass">Временные пропуска </a>
                                </li>
                                <li class="d-inline-flex align-items-center rounded " aria-current="page">
                                    <a asp-action="@nameof(PassTrackingSystem.Controllers.SinglePassController.ShowAll)"
                                       asp-controller="@nameof(PassTrackingSystem.Controllers.SinglePassController).Replace("Controller", "")"
                                       id="all-SinglePass">
                                        Разовые пропуска
                                    </a>
                                </li>
                                <li class="d-inline-flex align-items-center rounded " aria-current="page">
                                    <a asp-action="@nameof(PassTrackingSystem.Controllers.ShootingPermissionController.ShowAll)"
                                       asp-controller="@nameof(PassTrackingSystem.Controllers.ShootingPermissionController).Replace("Controller", "")"
                                       id="all-ShootingPermission">
                                        Разрешения на съемку
                                    </a>
                                </li>
                                <li class="d-inline-flex align-items-center rounded " aria-current="page">
                                    <a asp-action="@nameof(PassTrackingSystem.Controllers.CarPassController.ShowAll)"
                                       asp-controller="@nameof(PassTrackingSystem.Controllers.CarPassController).Replace("Controller", "")"
                                       id="all-CarPass">
                                        Транспортные пропуска
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    </li>
                    <button class="btn d-inline-flex align-items-center rounded" data-bs-toggle="collapse" data-bs-target="#about-collapse" aria-expanded="false">
                        Пользователи
                    </button>
                    
                    <div class="collapse show" id="about-collapse">
                        <ul class="list-unstyled fw-normal pb-1 small">
                            <li class="d-inline-flex align-items-center rounded " aria-current="page">
                                <a asp-action="@nameof(PassTrackingSystem.Controllers.AdminController.Show)"
                                   asp-controller="@nameof(PassTrackingSystem.Controllers.AdminController).Replace("Controller", "")"
                                   id="add-User">
                                    Добавить
                                </a>
                            </li>
                            <li class="d-inline-flex align-items-center rounded " aria-current="page">
                                <a asp-action="@nameof(PassTrackingSystem.Controllers.AdminController.ShowAll)"
                                   asp-controller="@nameof(PassTrackingSystem.Controllers.AdminController).Replace("Controller", "")"
                                   id="all-User">
                                    Просматреть все
                                </a>
                            </li>
                        </ul>
                    </div>
                    <li class="my-3 mx-4 border-top"></li>
                    <li>
                        <a class="d-inline-flex align-items-center rounded">
                            Выйти
                        </a>
                    </li>
                </ul>
            </nav>

        </aside>

        <main class="bd-main order-1">
            <div>
                @RenderBody()
            </div>
        </main>
    </div>


    <footer class="bd-footer p-3 p-md-5 mt-5 bg-light text-center text-sm-start">
    </footer>
<script>
    let elem = $('#currentPage').first().val()
    $(`#${elem}`).first().addClass('active')
</script>
</body>
</html>

PassTrackingSystem/Views/Shared/_OneItemComboBox.cshtml
@{
    Layout = "";
}
@model OneItemComboBoxVMExternal
<div class="input-group">
    <select class="form-select combobox-ontime-loader" selected-value="@Model.SelectedId" id="@Model.SelecterId"
            aria-label="Example select with button addon" asp-for=AspForValue>
    </select>
    <button class='btn btn-outline-secondary one-item-data-request'
            extend-button-purpose="@Model.ExtendButtonPurpose"
            data-bs-target="#exampleModal"
            data-bs-toggle="modal" type="button"           
            >
        <img src='/more-deteils.png'
             style="width: 21px;">
    </button>
</div>