PassTrackingSystem/Controllers/CarPassController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PassTrackingSystem.Extensions;
using PassTrackingSystem.Models;
using PassTrackingSystem.Models.Repositoryes;
using PassTrackingSystem.Models.SeparatorOnThePage;
using PassTrackingSystem.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PassTrackingSystem.Controllers
{
    [Authorize]
    public class CarPassController : Controller
    {
        private readonly IGenericRepository<CarPass> passRepository;
        private readonly IGenericRepository<Employee> employeeRepository;
        private readonly UserManager<AppUser> userManager;
        public CarPassController(IGenericRepository<CarPass> passRepository,
            IGenericRepository<Employee> employeeRepository, UserManager<AppUser> userManager)
        {
            this.passRepository = passRepository;
            this.employeeRepository = employeeRepository;
            this.userManager = userManager;
        }

        public async Task<IActionResult> CarPassProcessing(int id, int visitorId)
        {
            CarPass carPass;
            if (id != 0)
            {
                carPass = await passRepository.GetAll()
                    .Where(v => v.Id == id)
                    .Include(v => v.Car)
                    .Include(v => v.CarPassIssued)
                    .ThenInclude(v => v.Department)
                    .FirstAsync();
            }
            else
            {
                carPass = new CarPass();
                if (visitorId != 0)
                {
                    var user = await userManager.GetUserAsync(HttpContext.User);
                    var employee = await employeeRepository.Get(user.EmployeeId);
                    carPass.CarPassIssued = employee;
                    carPass.ValidWith = DateTime.Now;
                    carPass.ValitUntil = DateTime.Now;
                    carPass.VisitorId = visitorId;
                }
                else return new BadRequestResult();
            }
            return View(new CarPassVM
            {                
                ProcessingCarPass = carPass,
                ShowAdvancedFeatures = HttpContext.User.IsInRole("Administrator") || HttpContext.User.IsInRole("Moderator")
            });
        }

        [HttpPost, Authorize(Roles = "Moderator, Administrator")]
        public async Task<RedirectToActionResult> CarPassProcessing(CarPass ProcessingCarPass)
        {
            ModelState.Remove("ProcessingCarPass.Car.Id");
            if (ModelState.IsValid)
            {
                var user = await userManager.GetUserAsync(HttpContext.User);
                var employee = await employeeRepository.Get(user.EmployeeId);
                ProcessingCarPass.CarPassIssued = employee;
                await passRepository.Update(ProcessingCarPass);
                return RedirectToAction("CarPassProcessing", new { id = ProcessingCarPass.Id }); 
            }
            return RedirectToAction(nameof(CarPassController.BadRedirectRequest),
                    nameof(VisitorFormController));
        }

        public async Task<IActionResult> ShowAll(int? visitorId, CommonListQuery options = null)
        {
            var query = visitorId == null ? passRepository.GetAll() : passRepository.GetAll()
                .Where(v => v.VisitorId == visitorId);
            if(options.SearchСolumn == nameof(CarPass.Car.CarBrand))
            {
                query = query.Where(p => p.Car.CarBrand.Contains(options.SearchValue));
                options.SearchСolumn = "";
            }
            if (options.SearchСolumn == nameof(CarPass.Car.CarLicensePlate))
            {
                query = query.Where(p => p.Car.CarLicensePlate.Contains(options.SearchValue));
                options.SearchСolumn = "";
            }
            var passes = Task.Run(() => new PagesDividedList<CarPass>(query
                .Include(v => v.Car)
                  .Include(v => v.CarPassIssued)
                  .ThenInclude(v => v.Department)
                     .SearchByMember(options.SearchСolumn, options.SearchValue)
                        .OrderByMember("Id", true), options.CurrentPage, options.PageSize));
            if (visitorId != 0)
            {
                ViewBag.CurrentPage = "all-CarPass";
            }
            var TemporaryPasses = await passes;
            return View(new CarPassVM { CarPasses = await passes, PurposeVisitorId = visitorId, 
                ShowAdvancedFeatures = HttpContext.User.IsInRole("Administrator") || HttpContext.User.IsInRole("Moderator") });
        }

        public async Task<IActionResult> Document(int passId, bool itsForDocument = true)
        {
            if (passId != 0)
            {
                var pass = await passRepository.GetAll()
                    .Where(p => p.Id == passId)
                    .Include(p => p.Visitor).ThenInclude(v => v.Document).ThenInclude(d => d.DocumentType)
                    .Include(p => p.Visitor).ThenInclude(v => v.Document).ThenInclude(d => d.IssuingAuthority)
                    .Include(p=> p.Car)
                    .FirstAsync();

                var documentVM = new CommonInformationVM
                {
                    Document = pass.Visitor.Document,
                    Id = pass.Id,
                    Name = pass.Visitor.Name,
                    LastName = pass.Visitor.LastName,
                    Patronymic = pass.Visitor.LastName,
                    PassType = "Транспортный пропуск",
                    ValidWith = pass.ValidWith.ToLongDateString(),
                    ValitUntil = pass.ValitUntil.ToLongDateString(),
                    PlaceOfWork = pass.Visitor.PlaceOfWork,
                    Position = pass.Visitor.Position,
                    PurposeOfIssuance = pass.PurposeOfIssuance,
                    Car = pass.Car
                };
                if (itsForDocument)
                {
                    return View("Document", documentVM);
                }
                if (!itsForDocument)
                {
                    return View("CommonPassInfo", documentVM);
                }
            }
            return BadRequest();
        }

        [HttpPost, Authorize(Roles = "Moderator, Administrator")]
        public async Task<IActionResult> Delete(int id)
        {
            if (id != 0)
            {
                await passRepository.Delete(id);
            }
            return new OkResult();
        }

        public IActionResult BadRedirectRequest() => BadRequest();
    }
}

PassTrackingSystem/Views/CarPass/CarPassProcessing.cshtml
@model CarPassVM
<form method="post" asp-controller="CarPass" , asp-action="CarPassProcessing">
    <div class="container-fluid set-min-width">
        <input type="hidden" asp-for="ProcessingCarPass.Id" id="pass-id" />
        <input type="hidden" asp-for="ProcessingCarPass.VisitorId" />
        <input type="hidden" asp-for="ProcessingCarPass.Car.Id" />
        <div class="row">
            <div class="col-md-6">
                <label asp-for="ProcessingCarPass.Car.CarBrand" class="form-label">Марка авто</label>
                <input asp-for="ProcessingCarPass.Car.CarBrand" class="form-control">
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label asp-for="ProcessingCarPass.Car.CarLicensePlate" class="form-label">Номерной знак</label>
                <input asp-for="ProcessingCarPass.Car.CarLicensePlate" class="form-control">
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label asp-for="ProcessingCarPass.ValidWith" class="form-label">Действует с</label>
                <input asp-for="ProcessingCarPass.ValidWith" class="form-control">
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label asp-for="ProcessingCarPass.ValitUntil" class="form-label">Действует по</label>
                <input asp-for="ProcessingCarPass.ValitUntil" class="form-control">
            </div>
        </div>
        <div class="row">
            <div class="col-md-7">
                <label asp-for="ProcessingCarPass.PurposeOfIssuance" class="form-label">Цель выдачи</label>
                <textarea asp-for="ProcessingCarPass.PurposeOfIssuance" class="form-control" rows="8"></textarea>
            </div>
        </div>
    </div>
    <div id="access-list">
    </div>
    <div class="pt-4 bd-example">
        <label>Сотрудник выдавший документ</label>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Имя</th>
                    <th scope="col">Фамилия</th>
                    <th scope="col">Отчество</th>
                    <th scope="col">Подразделение</th>
                    <th scope="col">Должность</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model?.ProcessingCarPass?.CarPassIssued?.LastName</td>
                    <td>@Model?.ProcessingCarPass?.CarPassIssued?.Name</td>
                    <td>@Model?.ProcessingCarPass?.CarPassIssued?.Patronymic</td>
                    <td>@Model?.ProcessingCarPass?.CarPassIssued?.Department?.Value</td>
                    <td>@Model?.ProcessingCarPass?.CarPassIssued?.Position</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="py-5 ">
        <button type="submit" class="btn btn-success">Отправить</button>
        <button type="reset" class="btn btn-danger">Очистить</button>
        @if (Model.ProcessingCarPass?.Id != 0)
        {
            <a class="btn btn-info"
               asp-controller=@nameof(CarPassController).Replace("Controller", "")
               asp-action="@nameof(CarPassController.Document)" asp-route-passId="@Model.ProcessingCarPass.Id">Генерировать документ</a>
        }
    </div>

</form>

PassTrackingSystem/Views/CarPass/ShowAll.cshtml
@model CarPassVM

@{
    ViewData["Title"] = "Home Page";
}

<div class="col-12">
    <form asp-action="@nameof(PassTrackingSystem.Controllers.CarPassController.ShowAll)"
          asp-controller="@nameof(PassTrackingSystem.Controllers.CarPassController).Replace("Controller", "")"
          id="info-option-group" method="get">
        @await Html.PartialAsync("UpperOptionMenu", @Model)
        <input type="hidden" value="@Model.PurposeVisitorId" name="visitorId" />
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col" class="th-sm">id</th>
                    <th scope="col">Действует с</th>
                    <th scope="col">Действует по</th>
                    <th scope="col">Цель выдачи</th>
                    <th scope="col">Марка автомобиля</th>
                    <th scope="col">Номерной знак</th>
                    <th scope="col">Лицо выдавшее пропуск</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var CarPass in Model.CarPasses.Items)
                {
                    <tr>
                        <td>@CarPass.Id</td>
                        <td>@CarPass?.ValidWith.ToShortDateString()</td>
                        <td>@CarPass?.ValitUntil.ToShortDateString()</td>
                        <td>@CarPass?.PurposeOfIssuance</td>
                        <td>@CarPass?.Car?.CarBrand</td>
                        <td>@CarPass?.Car?.CarLicensePlate</td>
                        <td>@CarPass?.CarPassIssued?.LastName @CarPass.CarPassIssued?.Name @CarPass.CarPassIssued?.Patronymic</td>
                        <td>
                            <a asp-action="@nameof(PassTrackingSystem.Controllers.CarPassController.CarPassProcessing)"
                               asp-controller="@nameof(PassTrackingSystem.Controllers.CarPassController).Replace("Controller", "")"
                               asp-route-id="@CarPass.Id"
                               class="btn btn-outline-dark">Подробнее</a>
                        </td>
                        @if (Model.ShowAdvancedFeatures)
                        {
                            <td>
                                <button class="btn btn-outline-danger delete" del-id="@CarPass.Id">
                                    Удалить
                                </button>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
        @await Html.PartialAsync("Pages", @Model.CarPasses.PageDividorInfo)
    </form>
    <script>
        $('.delete').click(function (e) {
            $.post('@Url.RouteUrl(new { controller = nameof(CarPassController).Replace("Controller", ""),
              action = nameof(CarPassController.Delete)})', { id: $(this).attr('del-id') }, function () { location.reload()})
              e.preventDefault()
        })
    </script>
</div>